_BASE_: default.yaml
exp_name: rockley_nonlinear_regression
trainer:
  max_epochs: 100
data_module:
  name: RockleyDataModule
  shape: [197]
val_epoch_vis_freq: 2
test_batch_vis_freq: 1000
model:
  sampler:
    name: LOUPESampler
    input_size: 197
  predictor:
    name: NonlinearRegressor
    input_size: 197
train_loss:
  name: MSELoss
val_test_loss:
  name: MSELoss