_BASE_: default.yaml
exp_name: sample_regression
trainer:
  max_epochs: 10
data_module:
  name: SampleDataModule
  shape: [10]
val_epoch_vis_freq: 2
test_batch_vis_freq: 1000
model:
  sampler:
    name: IdentitySampler
  predictor:
    name: LinearRegressor
    input_size: 10
  learning_rate: 1
train_loss:
  name: MSELoss
val_test_loss:
  name: MSELoss
lr: 0.01